#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
from bs4 import BeautifulSoup
from prettytable import *
import xlwt
import os
import datetime
import datetime
from decimal import Decimal
import numpy as np

def make_excel(excel_file, data):
    """
    制作excel表格文件
    :param excel_file: excel 文件
    :param data: excel 数据
    :return: excel报表文件
    """
    # 已存在就删除
    if os.path.exists(excel_file):
        os.remove(excel_file)

    book = xlwt.Workbook()
    sheet = book.add_sheet("focus_fund", cell_overwrite_ok=True)
    topic_row = ['Code', 'Date', 'NAV', 'Change']

    # 标题行
    for n in range(len(topic_row)):
        sheet.write(0, n, topic_row[n])
    # 数据行
    i_row = 0
    for i1, row in enumerate(data, start=1):
        for i2,cell in enumerate(row, start=1):
            i_row = i_row + 1
            sheet.write(i_row, 0, cell['Code'])
            sheet.write(i_row, 1, cell['Date'])
            sheet.write(i_row, 2, cell['NetAssetValue'])
            sheet.write(i_row, 3, cell['ChangePercent'])
    book.save(excel_file)

def get_url(url, params=None, proxies=None):
    rsp = requests.get(url, params=params, proxies=proxies)
    rsp.raise_for_status()
    return rsp.text

def get_fund_data(code, page, start='', end=''):
    record = {'Code': code}
    url = 'http://fund.eastmoney.com/f10/F10DataApi.aspx'
    params = {'type': 'lsjz', 'code': code, 'page': page, 'per': 65535, 'sdate': start, 'edate': end}
    html = get_url(url, params)
    soup = BeautifulSoup(html, 'html.parser')
    records = []
    tab = soup.findAll('tbody')[0]
    for tr in tab.findAll('tr'):
        if tr.findAll('td') and len((tr.findAll('td'))) == 7:
            record['Date'] = str(tr.select('td:nth-of-type(1)')[0].getText().strip())
            record['NetAssetValue'] = str(tr.select('td:nth-of-type(2)')[0].getText().strip())
            record['ChangePercent'] = str(tr.select('td:nth-of-type(4)')[0].getText().strip())
            records.append(record.copy())
    return records

def get_fund(code_list,page_list, start= '', end=''):
    records_list = []
    for code in code_list:
        for page in page_list:
            records = get_fund_data(code, page, start='', end='')
            records_list.append(records)
    return records_list


def demo(code, start, end):
    table = PrettyTable()
    table.field_names = ['Code', 'Date', 'NAV', 'Change']
    table.align['Change'] = 'r'
    records = get_fund_data(code, start, end)
    for record in records:
        table.add_row([record['Code'], record['Date'], record['NetAssetValue'], record['ChangePercent']])
    return table


if __name__ == "__main__":
    tgt_file = "C:\\Users\\xn088969\\Desktop\\focus_fund.xls"
    code_list = ['166005','501029','519778','519727','202801','090010','006669','006868']
    page_list = list(np.arange(1,8))
    start = '2019-01-01'
    end = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d')
    records_list = get_fund(code_list,page_list, start, end)
    make_excel(tgt_file, records_list)
